### PR TITLE
Update broken.html

### PR DESCRIPTION
**Pull request by nisancigokmen**
- fixes #<issue number>

Checklist:

- [ ] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ ] Add or update relevant docs, in the docs folder and in code.
- [ ] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [ ] Add `.. versionchanged::` entries in any relevant code docs.
- [ ] Run `pre-commit` hooks and fix any issues.
- [ ] Run `pytest` and `tox`, no tests failed.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
uh what is this supposed to fix?

**Comment by nisancigokmen** [comment]
@ThiefMaster  `update.`

**Comment by nisancigokmen** [comment]
thanks:=)


Adrian ***@***.***>, 5 Oca 2022 Çar, 05:48 tarihinde şunu
yazdı:

**Comment by ThiefMaster** [comment]
your change makes no sense...

**Comment by nisancigokmen** [comment]
oh okay,sorry.I just wanted to support. made more sense. thank you. good work :100:

**Pull request closed without merging**
