### PR TITLE
Clarified and extended the docs for the `{select|reject}[attr]` filters.

### PR DESCRIPTION
**Pull request by homeworkprod**

### CODE REVIEW

**Comment by luzpaz** [comment]
bump

**Comment by jeffwidman** [comment]
I'm not seeing a typo that needs fixing? If it's still there, can you rebase?

**Comment by homeworkprod** [comment]
I've corrected four instances of "appying" to "applying".

However, that typo has been fixed by c251d8a, 21 months after my original PR.

My additional note (or something similar) to each of the four filters on how they behave if no test is given has not been added in the meantime, though.

Should I rebase?

**Comment by jeffwidman** [comment]
> My additional note (or something similar) to each of the four filters on how they behave if no test is given 

Yeah, I think this is worth including. Rebase appreciated.

**Comment by homeworkprod** [comment]
I have rebased. Please take a look.

I think the clarification of the docstring regarding the test being applied to *each* object of the sequence instead of "the object" prevents confusion, so I kept it.

**Pull request merged**
