### PR TITLE
Quick lookup table for builtin filters and tests-- references #584

### PR DESCRIPTION
**Pull request by doobeh**
Might need a little padding tweak to the CSS for spacing under the table.  References issue #584 

image

### CODE REVIEW

**Comment by ThiefMaster** [comment]
While it looks pretty, it's going to be an absolute pain in the ass to add a new test/filter to that table.

(also, from a semantic point of view, this isn't data that belongs in a table since the rows/cols are meaningless)

**Comment by doobeh** [comment]
I'll look into constructing something more automated-- similar to how the table directive for `jinja_filters` is built.  Can you think of a more semantic layout (py3 docs use the table layout for similar overviews).  Columns of lists I guess would be best and degrade well.

**Comment by davidism** [comment]
If the new pallets-sphinx-themes doesn't handle table spacing correctly, it should be easy to fix there. I do like how the layout is used in the Python docs, I agree that it should be automated though.

**Comment by davidism** [comment]
I'm going to merge this, but it's likely to get removed eventually. I'm working on improving the directives in [pallets-sphinx-themes](https://github.com/pallets/pallets-sphinx-themes).

**Pull request merged**
