### PR TITLE
add ImportLibResourceLoader

### LINKED ISSUE #970: Replace pkg_resource by importlib_resources
Hi.

Can you provide a future-proof loader that use `importlib_resources` instead of `pkg_resource`, which does not work pretty well in every case (on my pyinstaller package for instance it fails).

For me the use of `pkg_resource` should be avoided, it is about to be discarded (or maybe one day setuptools will not embed it). Providing a loader compatible with `importlib_resources` (the backport that brings' 3.7 `importlib.resources` to Python <3.7) is the easiest and more future-proof solution.

Thanks

### PR DESCRIPTION
**Pull request by gsemet**
closes #970

### CODE REVIEW

**Comment by tobywf** [comment]
Seems like by adding `tests/res/templates/__init__.py`, `*.pyc` files are being generated, which trips up the `FileSystemLoader` when trying to parse those as `utf-8`. I have a fix, but I'm unsure how to update somebody else's pull request. @gsemet, please let me know how you would like to handle this. Happy to cherry-pick your commit onto a fork and create new PR (retaining the original author, or resetting the commit's author if you prefer), or somehow update your fork and therefore this PR. Thanks!

**Comment by gsemet** [comment]
Oh if you know how to fix it, you can put a PR on top of my PR :)

**Comment by tobywf** [comment]
Please see #1023 and https://github.com/gsemet/jinja/pull/1 . Hope this helps!

**Comment by a-wakeel** [comment]
is this going to be fixed and merged soon?

**Comment by gsemet** [comment]
ok i have merged your pr but i will maybe redo it

**Comment by a-wakeel** [comment]
@gsemet when can i expect it to be merged into jinja?

**Comment by gsemet** [comment]
I’m looking to rebase it properly

**Comment by gsemet** [comment]
ok, should be ok now :)

**Comment by a-wakeel** [comment]
will wait for this to be merged

**Comment by davidism** [comment]
I really appreciate that you started work on this, getting rid of the dependency on setuptools and pkg_resources is good. I'm closing this in favor of #1082, which only updates the existing `PackageLoader` and avoids the constraints of `importlib.resources`.

**Pull request closed without merging**
