### PR TITLE
Update line statement lexer regexp to stop at the first newline

### PR DESCRIPTION
**Pull request by captainmalloc**
When using line statement prefix in Jinja2 templates it is impossible to add a blank line after the Jinja2 tag because successive newlines are recognized as TOKEN_LINESTATEMENT_END. 

The following example:
```
# for i in range(2)
#  for j in range(2)
{{i}}_{{j}}
#  endfor

# endfor
```
Will output:
```
0_0
0_1
1_0
1_1
```

A workaround is to add an explicit newline:
```
# for i in range(2)
#  for j in range(2)
{{i}}_{{j}}
#  endfor
{{'\n'}}
# endfor
```

With this simple fix, the lexer will recognize the end of the line statement at the first newline and allow the user to put empty lines as if (s)he is using blocks.

The given example will respect user wish to insert an empty line after each inner loop by generating the following output:
```
0_0
0_1

1_0
1_1

```

### CODE REVIEW

**Comment by davidism** [comment]
Did you mean to include your other PR in this PR? I don't want to deal with merge conflicts.

**Comment by captainmalloc** [comment]
I didn't mean to add those commits. I am sorry about that, I'll clean it on a new commit.

**Comment by davidism** [comment]
You can `git rebase -i master` then `git push -f` to clean it up.

**Comment by captainmalloc** [comment]
Done. Sorry for the inconvenience.

**Comment by davidism** [comment]
The fact that line statements behave the same as `-%}`  seems intentional. If you need to only strip one line, use `trim_blocks=True` with regular (not line) statements.

**Comment by captainmalloc** [comment]
IMHO line statement should be considered as "line" statement. There is not real reason to make them consume multiple lines when parsed.

This is why I am not  satisfied with your explanation and your decision to reject the this request.

**Comment by samuelcolvin** [comment]
I know this is an old PR, but I'll like to add my voice to support this PR.

Line statements looked like a create solution for my application of templated markdown files use by non technical people. 

But this problem means that they're basically useless for this application since text inside an `if` statement can never be its own paragraph.

**Comment by samuelcolvin** [comment]
surely stripping newlines after line statements should follow `trim_blocks` `True/False`

**Pull request closed without merging**
