### PR TITLE
Add namespace objects that support attribute assignment 

### PR DESCRIPTION
**Pull request by ThiefMaster**
This solves more complex cases affected by #641 where #676 is not sufficient.

Somewhat dumb example showing how it works:

```python
{% set ns = namespace(found=false) %}
{% for item in [1, 2, 3] %}
    {% set ns.found = item == 3 %}
{% endfor %}
Found: {{ ns.found }}
```

### CODE REVIEW

**Comment by untitaker** [comment]
@davidism I am not familiar enough with the codebase to review this. I think the addition to the language makes sense, in principle.

**Comment by davidism** [comment]
@untitaker I'm learning as I go too :-) but everything here seems fine.

@ThiefMaster given that @mitsuhiko suggested this in the first place, I think it's ok to merge. Same with #676.

**Comment by untitaker** [comment]
Yes, lgtm

On 5 April 2017 19:59:53 CEST, David Lord <notifications@github.com> wrote:
>@untitaker I'm learning as I go too :-) but everything here seems fine.
>
>@ThiefMaster given that @mitsuhiko suggested this in the first place, I
>think it's ok to merge. Same with #676.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/jinja/pull/684#issuecomment-291944877

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mitsuhiko** [comment]
I will have a look in a bit.

**Comment by mitsuhiko** [comment]
Namespaces should use `__setitem__` and `__getitem__` rather than real attributes. Otherwise we run at risk of letting users set special attributes which can cause security issues.

**Comment by mscheper** [comment]
Sorry to ask this here, but I couldn't find any general Jinja forums. It looks like this feature will be included in Jinja 2.10. Has this been scheduled for release, and is there a way to find out when that's likely?

**Comment by davidism** [comment]
As with all our projects, the release will happen when we have time. Sorry we can't be more specific than that, the maintainers do not have a lot of free time. As a workaround, you can do essentially the same thing as here by injecting a custom object with a function to set attributes.

**Comment by alanhamlett** [comment]
@mscheper also check out [#676#issuecomment-304051565](https://github.com/pallets/jinja/pull/676#issuecomment-304051565) with a solution using a custom template function to get/set globals if you're using Flask.

**Pull request merged**
