### PR TITLE
fix tests to pass on win32 - files must be closed before deletion.

### PR DESCRIPTION
**Pull request by mindw**

### CODE REVIEW

**Comment by jeffwidman** [comment]
Is this still an issue? I don't have Win32 around to test...

**Comment by mindw** [comment]
updated. You can you vagrant for it.
```
vagrant init Microsoft/EdgeOnWindows10; vagrant up --provider virtualbox
```
appveyour is a CI for windows - https://packaging.python.org/en/latest/appveyor/

**Comment by jeffwidman** [comment]
I'm not really competent to judge the correctness of this PR, as I'm not very familiar with Windows programming. Hopefully @DasIch can take another look. 

I asked the question because I was closing old PRs that were no longer relevant, and I hoped this fit in that category.

**Comment by davidism** [comment]
All tests pass on Windows for me, for Py 3.6 and 2.7.

**Pull request closed without merging**
