### PR TITLE
Make title filter capitalize words inside parens and other brackets

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by jgmize** [comment]
Updated to simplify the code.

**Comment by davidism** [comment]
What about the other brackets? `{ [ <`

**Comment by jgmize** [comment]
> What about the other brackets? { [ <

Good point, @davidism. I've updated the PR to handle those brackets as well, along with some performance optimizations.

**Comment by jeffwidman** [comment]
Thanks!

**Pull request merged**
