### PR TITLE
Add camelize filter

### PR DESCRIPTION
**Pull request by borismod**
camelize filter converts as following:

```
abstract_factory ➡️  AbstractFactory
abstract-factory ➡️  AbstractFactory
abstract factory  ➡️  AbstractFactory
AbstractGeneric-factory   ➡️  AbstractGenericFactory
```

### CODE REVIEW

**Comment by ThiefMaster** [comment]
I don't think this is that useful in the core of Jinja...

Also, general advice for PRs and feature branches in general: Rebase them to upstream instead of merging upstream. Having merge commits in a PR's branch is rather ugly.

**Comment by ThiefMaster** [comment]
Also, please do not perform formatting cleanups in unrelated PRs. As nice as having no trailing whitespace etc. is, it just adds noise to a PR whose objective is to add a new feature.

**Comment by ThiefMaster** [comment]
> AbstractGeneric-factory   ➡️  GenericAbstractFactory

Did you mean `AbstractGeneric-factory   ➡️  AbstractGenericFactory`?

**Comment by borismod** [comment]
@ThiefMaster thanks for your feedback. What alternative do you suggest instead of adding a filter when I need to camelize a string using Jinja?

**Comment by ThiefMaster** [comment]
You can add it in your application. It does not need to be part of Jinja itself.

http://jinja.pocoo.org/docs/dev/api/#writing-filters

**Comment by davidism** [comment]
I agree, adding this to your own app is trivial: install inflection, add relevant function to filters.

**Comment by borismod** [comment]
Dear @davidism and @ThiefMaster thank you for your comments. I understand that this filter can be added in application that consumes Jinja. In my case it's [Cookiecutter ](https://github.com/audreyr/cookiecutter)- a command line tool for creating projects based on templates.  At the end we're using Cookiecutter in [ShellFoundry ](https://github.com/QualiSystems/shellfoundry)- a command line utility for creating CloudShell shells.

Both tools are not aware of the set of filters that Jinja provides and use them as a black box. That's the way we consume dependencies. Camelize is a popular string manipulation that may be used by many users of Jinja in creating templates for their project. It converts a snake style string to Camel Case, for example code_generator.py to CodeGenerator, i.e. from file name to class name.

Can you please reconsider your decision and accept this PR ❓

**Comment by ThiefMaster** [comment]
It still sounds very code generation specific so me so it's something I'd rather to inside cookiecutter's code (i.e. do a PR against cookiecutter to add this, and possibly also the reverse, i.e. snakify)

**Pull request closed without merging**
