### PR TITLE
Finalize should only apply to variable #63

### PR DESCRIPTION
**Pull request by godsarmy**
I submit this PR to resolve the issue of #63 as i believe it is incorrect to apply finalize to any value in the template (constant, condition).

I think the root cause is self-explaining in the unit test "<{{ none }} >" as the original implementation tried to change none to empty string. However, none is not a variable in context but a constant, so instead, it should not be applied with finalize function.

```
tmpl = env.from_string('<{{ none }}>')
```

### CODE REVIEW

**Comment by davidism** [comment]
The lower case versions `none`, `true`, and `false`, are equivalent to their uppercase Python names in Jinja.  Even if the variable was changed to be a truly undefined value, undefined values are changed to `none` by default.  Changing `none` to `''` is correct in this case.

**Comment by LizardM4** [comment]
As a side remark, if `finalize` were not to be called on the template source, this would enable a much higher degree of customization -- one could autoescape the variables for languages other than HTML (see e.g. [this question on SO](http://stackoverflow.com/q/8001986/1749822), which originally brought me here).

**Comment by and1er** [comment]
What the status of this PR? Is the problem with LaTeX autoescape still cannot be solved https://stackoverflow.com/q/8001986/7444782 ?

**Comment by davidism** [comment]
`{{ none }}` is still an expression, just one that has been optimized to a constant. There is a distinction between static template data and constant expressions. All expressions should pass through finalize, template data should not.

**Pull request closed without merging**
