### PR TITLE
Fix typo on filter name

### PR DESCRIPTION
**Pull request by vbuxbaum**
Hi everyone!

I was studying Jinja and Flask with @JefersonViana , and noticed a typo in the docs about custom filters.

I hope there is no need for creating an issue for this.

Let me know if you think that there is a better solution.

### CODE REVIEW

**Comment by davidism** [comment]
The typo would be in the use, not the registration. Always prefer separated words, so `|datetime_filter`. (Yes, "datetime" itself doesn't follow this, but it's the built-in name.)

**Comment by davidism** [comment]
Be sure to make docs fixes against the latest feature branch (3.1.x) rather than main so that it gets into the current docs. You'll need to rebase and force push to fix that:

```
$ git rebase --onto origin/3.0.x origin/main
$ git push -f
```

**Comment by vbuxbaum** [comment]
> Be sure to make docs fixes against the latest feature branch (3.1.x) 

Thanks @davidism ! I did not pay attention to that, sorry. Done ✅ 

> The typo would be in the use, not the registration. Always prefer separated words, so `|datetime_filter`. (Yes, "datetime" itself doesn't follow this, but it's the built-in name.)

I also prefer naming separating words with `_`, but I think it is better if the filter function and the register in `environment.filters` have different names. Someone (mainly beginners) may wonder 

- _"is it necessary to keep the same name?"_ 
- or even _"which should be used inside the template? the function's name or the string registered in `environment.filters`"_

What if we rename the `datetime_format` function to `datetime_format_filter`, and keep the filter's name as `datetime_format`?

**Comment by davidism** [comment]
`datetime_format` everywhere please.

**Comment by vbuxbaum** [comment]
> `datetime_format` everywhere please.

@davidism done ✅

**Comment by vbuxbaum** [comment]
The `pre-commit.ci` failure has nothing to do with my changes, right? Do I need to do something about it?

**Pull request merged**
