### PR TITLE
[2.11.x] Restrict MarkupSafe < 2.1

### PR DESCRIPTION
**Pull request by 3nprob**
#1605 #1585 #1601 #1600 #1599 #1598 #1595 #1596 #1597 #1594 #1590 #1591 #1587 #1585

### CODE REVIEW

**Comment by 3nprob** [comment]
CI seems to assume `master` as base - this should be mergable without conflicts

**Comment by ThiefMaster** [comment]
It's an old and unsupported version... we do not plan to make a release adding upper bounds; people would have to update their pin anyway, so they can simply add the pin on markupsafe instead..

**Comment by 3nprob** [comment]
Those who did not add an explicit pin (very much like jinja itself) have had things not breaking without intervention. Those are now failing. Publishing this change will make it work againa without depending projects adding explicit pins.

**Comment by ThiefMaster** [comment]
People who did not pin Jinja would have gotten updates for both Jinja and Markupsafe -> no problem. So the only people are affected are these where *only* some of the deps are pinned...

**Pull request closed without merging**
