### PR TITLE
ignore errno.ENOTDIR in open_if_exists

### LINKED ISSUE #821: FileSystemLoader: {% import foo/test %} fails if there are templates 'foo' and 'foo/test'
Consider the `FileSystemLoader([dir1, dir2])`, where `dir1` containers `foo` template, while `dir2` contains directory `foo` with file `test`.

## Expected Behavior
The `env.get_template('foo/test')` should return proper template.

## Actual Behavior
The `env.get_template('foo/test')` raises
-> `IOError: [Errno 20] Not a directory: 'dir1/foo/test'`

## Full Traceback
```
IOError: [Errno 20] Not a directory: 'dir1/foo/test'
>>> from jinja2 import FileSystemLoader, Environment
>>> loader = FileSystemLoader(['dir1', 'dir2'])
>>> env = Environment(loader=loader)
>>> env.get_template('foo/test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python2.7/site-packages/jinja2/loaders.py", line 171, in get_source
    f = open_if_exists(filename)
  File "/usr/lib/python2.7/site-packages/jinja2/utils.py", line 154, in open_if_exists
    return open(filename, mode)
IOError: [Errno 20] Not a directory: 'dir1/foo/test'
```

## Your Environment
* Python version: any
* Jinja version: any

### PR DESCRIPTION
**Pull request by praiskup**
Fixes #821

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Check if there's a testcase for the other error cases; if there is one add one for this one as well, otherwise I think it's not needed (unless you want to cover it of course)

**Comment by ishakir** [comment]
Given that #839 has been closed, is there anything blocking this one being merged?

**Comment by praiskup** [comment]
@ThiefMaster sorry for late reply, no there haven't been tests for open_if_exists yet.  It would be nice if we could merge this as-is; otherwise let me know if something needs to be changed.

**Comment by davidism** [comment]
Would you add a changelog entry for this?

**Comment by praiskup** [comment]
Done, please take a look.

**Comment by praiskup** [comment]
The CI failure isn't related to this PR, am I right?

**Comment by ishakir** [comment]
CI failure definitely not related to this change. Only failing on Python 3.3 with some venv error

**Comment by ishakir** [comment]
Any reason this cannot be merged?

**Comment by tsopokis** [comment]
Is there a reason this is not merged? I face the same issue.

**Comment by praiskup** [comment]
@davidism may I do something for this PR?

**Comment by davidism** [comment]
Sorry, forgot this happens when I rename branches. Can you resubmit this against master?

**Comment by praiskup** [comment]
On Tuesday, March 19, 2019 9:05:14 PM CET David Lord wrote:
> Sorry, forgot this happens when I rename branches. Can you resubmit this against master?

Of course, I'll take a look at this tomorrow (ooo now).

**Comment by kevin-brown** [comment]
This is going to need to be rebased against the latest `2.10.x` branch. Right now there is a build running against Python 3.3 which is failing, and in the latest copy of that branch we no longer test against Python 3.3 (because it is EOL).

**Comment by praiskup** [comment]
I thought we can close this, and keep only #963?

**Pull request closed without merging**
